---
# Common application settings
application:
  name: registrationService

# Metrics configuration
metrics:
  enabled: true
  export:
    datadog:
      enabled: false

# Base configuration
grpc:
  port: 50051
registration:
  use_ldap: false
  directory:
    # Directory service type
    type: "entra_id"
    entra_id:
      tenant_id: ""
      client_id: ""
      client_secret: ""
      phone_number_attribute: "mobilePhone"
  grpc:
    timeout_secs: 30
    server:
      endpoint: "127.0.0.1"
      port: 50051
      timeout_secs: 30
  session_timeout_secs: 300
  rate_limits:
    check_verification_code:
      delays: 60
    leaky_bucket:
      session_creation:
        name: registration
        max_capacity: 100
        leak_rate: 0.1
        initial_tokens: 100
        permit_regeneration_period: 10
        min_delay: 25
    send_sms_verification_code:
      delays: 10
    send_voice_verification_code:
      delays: 60
      max_attempts: 3
      delay_after_first_sms: 300
