---
# Common application settings
application:
  name: registrationService

# Metrics configuration
metrics:
  enabled: true
  export:
    datadog:
      enabled: false

# Base configuration
grpc:
  port: 50051
registration:
  use_ldap: false
  grpc:
    host: "127.0.0.1"
    port: 50051
  directory:
    # Directory service type
    type: "entra_id"
    entra_id:
      tenant_id: "2f8b8c95-8509-4822-a393-dc8f12d2c829"
      client_id: "bcd5ed86-07a1-4528-9c44-32e86b3e79ee"
      client_secret: "${ENTRA_CLIENT_SECRET}"
      phone_number_attribute: "mobilePhone"
  dynamodb:
    enabled: true
    table_name: "registration_service"
    endpoint: "http://127.0.0.1:8000"
    region: "us-west-2"
  twilio:
    enabled: false
    verification_timeout_secs: 300
  rate_limits:
    check_verification_code:
      delays: 60
    leaky_bucket:
      session_creation:
        name: registration
        max_capacity: 100
        leak_rate: 0.1
        initial_tokens: 100
        permit_regeneration_period: 10
        min_delay: 25
    send_sms_verification_code:
      delays: 10
    send_voice_verification_code:
      delays: 60
      max_attempts: 3
      delay_after_first_sms: 300
