ldap:
  url: "ldap://localhost:389"
  bind_dn: "cn=admin,dc=example,dc=com"
  bind_password: "${LDAP_BIND_PASSWORD}"
  search_base: "dc=example,dc=com"
  search_filter: "(uid={})"
  phone_number_attribute: "mobile"
  connection_pool_size: 10
  timeout_secs: 30

twilio:
  account_sid: "${TWILIO_ACCOUNT_SID}"
  auth_token: "${TWILIO_AUTH_TOKEN}"
  verify_service_sid: "${TWILIO_VERIFY_SERVICE_SID}"
  verification_timeout_secs: 600

dynamodb:
  table_name: "signal_accounts"
  region: "us-west-2"
  endpoint: "http://localhost:8000"  # For local development

server:
  host: "127.0.0.1"
  port: 8080
  grpc_port: 50051

rate_limits:
  session_creation:
    max_attempts: 5
    window_secs: 300
  verification:
    max_attempts: 3
    window_secs: 600
